import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy · Entry",
  description:
    "Privacy Policy for Entry — what we collect, how we use it, and your rights.",
};

const EFFECTIVE_DATE = "26 April 2026";

export default function PrivacyPage() {
  return (
    <main style={pageStyle}>
      <article style={articleStyle}>
        <h1 style={h1Style}>Privacy Policy</h1>
        <p style={metaStyle}>Effective {EFFECTIVE_DATE}</p>

        <p>
          This Privacy Policy explains what personal data Entry Limited
          (&ldquo;we&rdquo;) collects, why we collect it, how we use it, and
          the choices you have. Entry is the events platform powering ticket
          sales, the rep ambassador programme, and the Entry mobile apps for
          iOS and Android.
        </p>

        <h2 style={h2Style}>1. Data we collect</h2>
        <p>We collect data you give us directly and data generated by your use of the Service.</p>

        <h3 style={h3Style}>You give us</h3>
        <ul style={ulStyle}>
          <li>
            <strong>Account info</strong> — email address, password (hashed),
            display name, optional profile photo.
          </li>
          <li>
            <strong>Profile info (rep app)</strong> — first/last name, optional
            phone number, gender, bio, Instagram and TikTok handles.
          </li>
          <li>
            <strong>Purchase info</strong> — name, email, phone, billing
            address, and payment details. Payment card details are handled
            directly by Stripe; we never see or store full card numbers.
          </li>
          <li>
            <strong>User-generated content</strong> — stories, quest
            submissions (including photos and screenshots you upload), reports
            of other users.
          </li>
        </ul>

        <h3 style={h3Style}>We collect automatically</h3>
        <ul style={ulStyle}>
          <li>
            <strong>Device info</strong> — device type, OS version, app
            version, language, timezone.
          </li>
          <li>
            <strong>Push tokens</strong> — APNs, FCM, or web-push endpoints if
            you enable notifications, used solely to send you the
            notifications you opted in to.
          </li>
          <li>
            <strong>Usage data</strong> — pages and screens viewed, taps,
            errors, crash reports. Used to debug, improve the app, and detect
            abuse.
          </li>
          <li>
            <strong>Approximate location</strong> — derived from your IP
            address to choose the right currency and to show events near you.
            We do not access precise device GPS.
          </li>
        </ul>

        <h2 style={h2Style}>2. How we use your data</h2>
        <ul style={ulStyle}>
          <li>To provide the Service — process ticket purchases, validate scans, run the rep programme.</li>
          <li>To send you transactional messages (order confirmations, ticket emails, password resets).</li>
          <li>
            To send marketing emails from the relevant Promoter, only if you
            opted in. You can unsubscribe at any time from the link in every
            email.
          </li>
          <li>To send push notifications you have enabled in the app.</li>
          <li>To prevent fraud and abuse, including detecting fake accounts and unauthorised resale.</li>
          <li>To comply with legal obligations (tax, accounting, lawful requests from authorities).</li>
        </ul>

        <h2 style={h2Style}>3. Who we share data with</h2>
        <p>
          We share your data only as needed to operate the Service and only
          with the following categories of recipients:
        </p>
        <ul style={ulStyle}>
          <li>
            <strong>Promoters</strong> — when you buy a ticket, the Promoter
            running the event receives your name, email, and ticket type so
            they can manage attendance and communicate with you. When you
            join a Promoter&apos;s rep team, they see your profile and your
            performance metrics within their team.
          </li>
          <li>
            <strong>Service providers</strong> — Stripe (payments), Supabase
            (database and storage), Vercel (hosting), Resend (email), Mux
            (video), Sentry (error monitoring), Klaviyo (marketing email if
            opted in), Apple and Google (push notifications and Wallet
            passes). These providers are bound by contract to handle your
            data only for the purposes we specify.
          </li>
          <li>
            <strong>Authorities</strong> — when required by law, court order,
            or to protect the safety of users.
          </li>
        </ul>
        <p>We do not sell your personal data.</p>

        <h2 style={h2Style}>4. User-generated content and moderation</h2>
        <p>
          Stories, quest submissions, and other user-posted content are
          visible within the app to other users in your audience scope (your
          Promoter&apos;s team, your followers, or the public quest feed).
          Every surface includes a report button. Reports are reviewed by
          Entry and the relevant Promoter. Confirmed violations result in
          content removal. We aim to act on reports within 24 hours.
        </p>
        <p>
          You can delete your own stories and quest submissions from the app.
          Once deleted, they are removed from public view; copies may persist
          in our backups for up to 30 days.
        </p>

        <h2 style={h2Style}>5. Your rights</h2>
        <p>
          Depending on where you live, you may have the right to access,
          correct, delete, port, or restrict the processing of your personal
          data. You can exercise these rights:
        </p>
        <ul style={ulStyle}>
          <li>From within the app — Settings &rarr; Account.</li>
          <li>
            By emailing{" "}
            <a href="mailto:privacy@entry.events" style={linkStyle}>
              privacy@entry.events
            </a>
            .
          </li>
        </ul>
        <p>
          You can withdraw consent for marketing emails at any time using the
          unsubscribe link or your account settings.
        </p>

        <h2 style={h2Style}>6. Account deletion</h2>
        <p>
          You can delete your account from within the app (Settings &rarr;
          Delete account). Account deletion immediately revokes your access,
          scrubs your personal identifiers (name, email, profile photo, phone,
          bio, social handles), and removes your push subscriptions. Records
          required for tax, accounting, or fraud prevention are retained per
          legal obligation; ledger entries tied to your purchases are
          preserved for the relevant Promoter.
        </p>

        <h2 style={h2Style}>7. Data retention</h2>
        <ul style={ulStyle}>
          <li>Account profile — until you delete your account.</li>
          <li>Order and ticket records — 7 years (legal accounting requirement).</li>
          <li>Push tokens — until you disable notifications or delete your account.</li>
          <li>Backups — up to 30 days from deletion.</li>
          <li>Crash and error reports — 90 days.</li>
        </ul>

        <h2 style={h2Style}>8. International transfers</h2>
        <p>
          Entry&apos;s primary infrastructure is hosted in the European Union
          (Supabase EU-West). Some service providers (Stripe, Vercel, Sentry,
          Apple, Google) may process data in other regions. Where required,
          transfers are protected by Standard Contractual Clauses or
          equivalent safeguards.
        </p>

        <h2 style={h2Style}>9. Children</h2>
        <p>
          Entry is not directed at children under 16 (or the age of digital
          consent in your country). If you believe a child has provided us
          with personal data, contact us and we will delete it.
        </p>

        <h2 style={h2Style}>10. Security</h2>
        <p>
          We use industry-standard measures to protect your data, including
          encryption in transit (TLS), encryption at rest, hashed passwords,
          and access controls. No system is perfectly secure; if we discover
          a breach we will notify affected users and the relevant authorities
          per applicable law.
        </p>

        <h2 style={h2Style}>11. Changes to this policy</h2>
        <p>
          We may update this Privacy Policy from time to time. Material
          changes will be communicated through the app or by email at least
          14 days before they take effect.
        </p>

        <h2 style={h2Style}>12. Contact</h2>
        <p>
          Privacy questions or requests:{" "}
          <a href="mailto:privacy@entry.events" style={linkStyle}>
            privacy@entry.events
          </a>
          .
        </p>
      </article>
    </main>
  );
}

const pageStyle: React.CSSProperties = {
  minHeight: "100vh",
  background: "#0a0a0a",
  color: "#e6e6e6",
  fontFamily:
    "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  padding: "48px 24px",
  lineHeight: 1.6,
};

const articleStyle: React.CSSProperties = {
  maxWidth: 720,
  margin: "0 auto",
};

const h1Style: React.CSSProperties = {
  fontSize: 32,
  fontWeight: 700,
  marginBottom: 8,
};

const h2Style: React.CSSProperties = {
  fontSize: 20,
  fontWeight: 600,
  marginTop: 32,
  marginBottom: 12,
};

const h3Style: React.CSSProperties = {
  fontSize: 16,
  fontWeight: 600,
  marginTop: 20,
  marginBottom: 8,
};

const ulStyle: React.CSSProperties = {
  paddingLeft: 20,
  marginBottom: 12,
};

const metaStyle: React.CSSProperties = {
  fontSize: 13,
  color: "#888",
  marginBottom: 32,
};

const linkStyle: React.CSSProperties = {
  color: "#a78bfa",
  textDecoration: "underline",
};
