"use client";

import { useEffect, useState, useCallback, useRef } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import {
  Table,
  TableHeader,
  TableBody,
  TableHead,
  TableRow,
  TableCell,
} from "@/components/ui/table";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import {
  Plus,
  Loader2,
  Check,
  X,
  Eye,
  Swords,
  Pencil,
  Trash2,
  CheckCircle2,
  ExternalLink,
  Music,
  Camera,
  Link as LinkIcon,
  Type,
  Image as ImageLucide,
  Upload,
  Video,
  AlertCircle,
  ArrowLeft,
  Sparkles,
  Target,
  ZoomIn,
  Inbox,
  Clock,
  Filter,
} from "lucide-react";
import dynamic from "next/dynamic";
import * as tus from "tus-js-client";
import { ImageUpload } from "@/components/admin/ImageUpload";
import { isMuxPlaybackId, getMuxThumbnailUrl } from "@/lib/mux";
import { getSupabaseClient } from "@/lib/supabase/client";
import { SUPABASE_URL, SUPABASE_ANON_KEY } from "@/lib/constants";
import { useOrgId } from "@/components/OrgProvider";

const MuxPlayer = dynamic(() => import("@mux/mux-player-react"), { ssr: false });

import type {
  RepQuest,
  QuestType,
  QuestStatus,
  RepQuestSubmission,
  PlatformXPConfig,
} from "@/types/reps";
import { DEFAULT_PLATFORM_XP_CONFIG } from "@/types/reps";

const QUEST_TYPE_LABELS: Record<QuestType, string> = {
  social_post: "Social Post",
  story_share: "Story Share",
  content_creation: "Content Creation",
  custom: "Custom",
  sales_milestone: "Sales Challenge",
};

const QUEST_AUTO_INSTRUCTIONS: Record<QuestType, string> = {
  social_post: "1. Watch the reference post\n2. Create your own version\n3. Post it and submit the link as proof",
  story_share: "1. Download the image or video below\n2. Share it to your Instagram/TikTok story\n3. Add your personal discount code & link to the story",
  content_creation: "1. Create original content about the event\n2. Post it on TikTok or Instagram\n3. Submit the link as proof",
  custom: "",
  sales_milestone: "",
};

const QUEST_FORM_TABS: Record<QuestType, string[]> = {
  social_post: ["Details", "Platform", "Content", "Publish"],
  story_share: ["Details", "Content", "Publish"],
  content_creation: ["Details", "Platform", "Content", "Publish"],
  custom: ["Details", "Setup", "Publish"],
  sales_milestone: ["Details", "Target", "Publish"],
};

const QUEST_STATUS_VARIANT: Record<QuestStatus, "success" | "warning" | "secondary" | "outline"> = {
  active: "success",
  paused: "warning",
  archived: "secondary",
  draft: "outline",
};

export function QuestsTab() {
  const orgId = useOrgId();
  const [quests, setQuests] = useState<RepQuest[]>([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState<"all" | QuestStatus>("active");

  // Create/Edit
  const [showDialog, setShowDialog] = useState(false);
  const [dialogStep, setDialogStep] = useState<"type" | "form">("type");
  const [formTab, setFormTab] = useState(0);
  const [editId, setEditId] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [questType, setQuestType] = useState<QuestType>("social_post");
  const [platform, setPlatform] = useState<"tiktok" | "instagram" | "any">("any");
  const [imageUrl, setImageUrl] = useState("");
  const [bannerImageUrl, setBannerImageUrl] = useState("");
  const [videoUrl, setVideoUrl] = useState("");
  const [pointsReward, setPointsReward] = useState("");
  const [maxCompletions, setMaxCompletions] = useState("");
  const [expiresAt, setExpiresAt] = useState("");
  const [instructions, setInstructions] = useState("");
  const [instructionsAutoGenerated, setInstructionsAutoGenerated] = useState(false);
  const [notifyReps, setNotifyReps] = useState(true);
  const [referenceUrl, setReferenceUrl] = useState("");
  const [usesSound, setUsesSound] = useState(false);
  const [currencyReward, setCurrencyReward] = useState("");
  const [salesTarget, setSalesTarget] = useState("");
  const [eventId, setEventId] = useState("");

  // Events list for event picker
  const [events, setEvents] = useState<Array<{ id: string; name: string }>>([]);

  // Video upload state
  const [videoUploading, setVideoUploading] = useState(false);
  const [videoProgress, setVideoProgress] = useState(0);
  const [videoStatus, setVideoStatus] = useState("");
  const [videoError, setVideoError] = useState("");
  const videoInputRef = useRef<HTMLInputElement>(null);

  // Platform XP config
  const [platformConfig, setPlatformConfig] = useState<PlatformXPConfig>(DEFAULT_PLATFORM_XP_CONFIG);

  // Submissions review — global view
  const [view, setView] = useState<"quests" | "submissions">("quests");
  const [allSubmissions, setAllSubmissions] = useState<RepQuestSubmission[]>([]);
  const [loadingAllSubs, setLoadingAllSubs] = useState(false);
  const [subFilter, setSubFilter] = useState<"pending" | "approved" | "rejected" | "all">("pending");
  const [questFilter, setQuestFilter] = useState<string | null>(null);
  const [reviewingId, setReviewingId] = useState<string | null>(null);
  const [rejectingId, setRejectingId] = useState<string | null>(null);
  const [rejectReason, setRejectReason] = useState("");
  const [lightboxUrl, setLightboxUrl] = useState<string | null>(null);

  const loadQuests = useCallback(async () => {
    setLoading(true);
    try {
      const params = new URLSearchParams();
      if (filter !== "all") params.set("status", filter);
      const res = await fetch(`/api/reps/quests?${params}`);
      const json = await res.json();
      if (json.data) setQuests(json.data);
    } catch { /* network */ }
    setLoading(false);
  }, [filter]);

  useEffect(() => { loadQuests(); }, [loadQuests]);

  // Fetch platform XP config + events on mount
  useEffect(() => {
    fetch("/api/platform/xp-config")
      .then((r) => r.json())
      .then((json) => { if (json.data) setPlatformConfig(json.data); })
      .catch(() => {});
    fetch("/api/events")
      .then((r) => r.json())
      .then((json) => { if (json.data) setEvents(json.data.map((e: { id: string; name: string }) => ({ id: e.id, name: e.name }))); })
      .catch(() => {});
  }, []);

  const loadAllSubmissions = useCallback(async () => {
    setLoadingAllSubs(true);
    try {
      const res = await fetch("/api/reps/submissions");
      const json = await res.json();
      if (json.data) setAllSubmissions(json.data);
    } catch { /* network */ }
    setLoadingAllSubs(false);
  }, []);

  // Auto-load submissions when switching to submissions view
  useEffect(() => {
    if (view === "submissions") loadAllSubmissions();
  }, [view, loadAllSubmissions]);

  const openCreate = () => {
    setEditId(null); setTitle(""); setDescription(""); setInstructions("");
    setInstructionsAutoGenerated(false);
    setQuestType("social_post"); setPlatform("any"); setImageUrl(""); setBannerImageUrl(""); setVideoUrl("");
    setPointsReward(String(platformConfig.xp_per_quest_type.social_post));
    setMaxCompletions(""); setExpiresAt(""); setNotifyReps(true);
    setReferenceUrl(""); setUsesSound(false); setCurrencyReward("0");
    setSalesTarget(""); setEventId("");
    setVideoError("");
    setDialogStep("type");
    setFormTab(0);
    setShowDialog(true);
  };

  const openEdit = (q: RepQuest) => {
    setEditId(q.id); setTitle(q.title); setDescription(q.description || "");
    setInstructions(q.instructions || ""); setInstructionsAutoGenerated(false);
    setQuestType(q.quest_type);
    setPlatform(q.platform || "any");
    setImageUrl(q.image_url || ""); setBannerImageUrl(q.banner_image_url || ""); setVideoUrl(q.video_url || "");
    setPointsReward(String(q.points_reward));
    setMaxCompletions(q.max_completions != null ? String(q.max_completions) : "");
    setExpiresAt(q.expires_at ? q.expires_at.slice(0, 16) : ""); setNotifyReps(q.notify_reps);
    setReferenceUrl(q.reference_url || ""); setUsesSound(q.uses_sound ?? false);
    setCurrencyReward(String(q.currency_reward || 0));
    setSalesTarget(q.sales_target != null ? String(q.sales_target) : "");
    setEventId(q.event_id || "");
    setVideoError("");
    setDialogStep("form");
    setFormTab(0);
    setShowDialog(true);
  };

  const handleSave = async () => {
    if (!title.trim()) return;
    setSaving(true);
    const body = {
      title: title.trim(), description: description.trim() || null,
      instructions: instructions.trim() || null, quest_type: questType, platform,
      image_url: imageUrl.trim() || null,
      banner_image_url: bannerImageUrl.trim() || null,
      video_url: videoUrl.trim() || null,
      points_reward: (platformConfig.xp_per_quest_type as Record<string, number>)[questType] ?? (Number(pointsReward) || 0),
      currency_reward: Number(currencyReward) || 0,
      max_completions: maxCompletions ? Number(maxCompletions) : null,
      expires_at: expiresAt || null, notify_reps: notifyReps,
      reference_url: referenceUrl.trim() || null, uses_sound: usesSound,
      sales_target: questType === "sales_milestone" && salesTarget ? Number(salesTarget) : null,
      event_id: eventId || null,
    };
    try {
      const url = editId ? `/api/reps/quests/${editId}` : "/api/reps/quests";
      const method = editId ? "PUT" : "POST";
      const res = await fetch(url, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
      if (res.ok) { setShowDialog(false); loadQuests(); }
    } catch { /* network */ }
    setSaving(false);
  };

  const handleDelete = async (id: string) => {
    try { await fetch(`/api/reps/quests/${id}`, { method: "DELETE" }); loadQuests(); } catch { /* network */ }
  };

  const handleReview = async (submissionId: string, newStatus: "approved" | "rejected", reason?: string) => {
    setReviewingId(submissionId);
    try {
      const res = await fetch(`/api/reps/quests/submissions/${submissionId}`, {
        method: "PUT", headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ status: newStatus, rejection_reason: reason }),
      });
      if (res.ok) {
        // Optimistic local update — keeps the card visible with new status
        setAllSubmissions(prev => prev.map(s =>
          s.id === submissionId ? { ...s, status: newStatus, rejection_reason: reason || s.rejection_reason } as RepQuestSubmission : s
        ));
        // Refresh quest pending counts
        loadQuests();
      }
    } catch { /* network */ }
    setReviewingId(null);
  };

  // Auto-generate instructions + auto-fill XP when quest type changes
  const handleQuestTypeChange = (newType: QuestType) => {
    const prevType = questType;
    setQuestType(newType);
    // Auto-fill XP from platform config (XP is platform-controlled, not tenant-editable)
    const xpForType = (platformConfig.xp_per_quest_type as Record<string, number>)[newType];
    if (xpForType !== undefined) setPointsReward(String(xpForType));
    // Auto-fill instructions if empty or were auto-generated
    const autoText = QUEST_AUTO_INSTRUCTIONS[newType];
    if (autoText && (!instructions.trim() || instructionsAutoGenerated)) {
      setInstructions(autoText);
      setInstructionsAutoGenerated(true);
    }
    // Clear story_share-specific fields when switching away
    if (prevType === "story_share" && newType !== "story_share") {
      setUsesSound(false);
    }
  };

  // Video upload handler (adapted from artists page)
  const handleVideoUpload = useCallback(async (file: File) => {
    setVideoError("");
    if (!file.type.startsWith("video/")) {
      setVideoError("Please select a video file (MP4, MOV, or WebM).");
      return;
    }
    const MAX_FILE_SIZE = 200 * 1024 * 1024;
    if (file.size > MAX_FILE_SIZE) {
      setVideoError(`Video is ${Math.round(file.size / 1024 / 1024)}MB — max is 200MB.`);
      return;
    }
    setVideoUploading(true);
    setVideoProgress(0);
    setVideoStatus("Preparing upload...");
    try {
      const supabase = getSupabaseClient();
      if (!supabase) throw new Error("Supabase not configured");
      const { data: { session } } = await supabase.auth.getSession();
      if (!session?.access_token) throw new Error("Not authenticated");

      const safeName = file.name.replace(/[^a-zA-Z0-9._-]/g, "_").toLowerCase();
      const storagePath = `${orgId}/quests/${Date.now()}_${safeName}`;
      const tusEndpoint = `${SUPABASE_URL}/storage/v1/upload/resumable`;

      setVideoStatus("Uploading...");
      await new Promise<void>((resolve, reject) => {
        const upload = new tus.Upload(file, {
          endpoint: tusEndpoint,
          retryDelays: [0, 3000, 5000, 10000, 20000],
          headers: { authorization: `Bearer ${session.access_token}`, apikey: SUPABASE_ANON_KEY, "x-upsert": "true" },
          uploadDataDuringCreation: true,
          removeFingerprintOnSuccess: true,
          chunkSize: 6 * 1024 * 1024,
          metadata: { bucketName: "artist-media", objectName: storagePath, contentType: file.type, cacheControl: "3600" },
          onError: (error) => reject(new Error(error.message || "Upload failed")),
          onProgress: (bytesUploaded, bytesTotal) => {
            setVideoProgress(Math.round((bytesUploaded / bytesTotal) * 70));
            setVideoStatus(`Uploading... ${(bytesUploaded / 1024 / 1024).toFixed(0)}/${(bytesTotal / 1024 / 1024).toFixed(0)} MB`);
          },
          onSuccess: () => resolve(),
          onShouldRetry: (err) => {
            const status = err.originalResponse?.getStatus();
            return status !== 403 && status !== 401;
          },
        });
        upload.findPreviousUploads().then((prev) => { if (prev.length) upload.resumeFromPreviousUpload(prev[0]); upload.start(); });
      });

      setVideoProgress(70);
      const publicUrl = `${SUPABASE_URL}/storage/v1/object/public/artist-media/${storagePath}`;
      setVideoStatus("Processing video...");
      const muxRes = await fetch("/api/mux/upload", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ videoUrl: publicUrl }) });
      const muxData = await muxRes.json();
      if (!muxRes.ok) throw new Error(muxData.error || "Failed to start processing");

      // Poll until ready
      for (let i = 0; i < 60; i++) {
        await new Promise((r) => setTimeout(r, 3000));
        const res = await fetch(`/api/mux/status?assetId=${muxData.assetId}`);
        const data = await res.json();
        if (data.status === "ready" && data.playbackId) { setVideoUrl(data.playbackId); setVideoProgress(100); setVideoStatus(""); setVideoUploading(false); return; }
        if (data.status === "errored") throw new Error("Mux processing failed");
        setVideoStatus("Processing video...");
      }
      throw new Error("Processing timed out");
    } catch (e) {
      const msg = e instanceof Error ? e.message : "Unknown error";
      setVideoError(`Upload failed — ${msg}`);
      setVideoStatus("");
    }
    setVideoUploading(false);
    setVideoProgress(0);
  }, [orgId]);

  const filtered = filter === "all" ? quests : quests.filter((q) => q.status === filter);
  const counts = {
    all: quests.length,
    active: quests.filter((q) => q.status === "active").length,
    paused: quests.filter((q) => q.status === "paused").length,
    archived: quests.filter((q) => q.status === "archived").length,
  };
  const totalPending = quests.reduce((sum, q) => sum + (q.pending_count || 0), 0);

  // Submissions view: filtered list
  const filteredSubs = allSubmissions.filter(s => {
    if (subFilter !== "all" && s.status !== subFilter) return false;
    if (questFilter && s.quest_id !== questFilter) return false;
    return true;
  });
  const subCounts = {
    all: allSubmissions.filter(s => !questFilter || s.quest_id === questFilter).length,
    pending: allSubmissions.filter(s => s.status === "pending" && (!questFilter || s.quest_id === questFilter)).length,
    approved: allSubmissions.filter(s => s.status === "approved" && (!questFilter || s.quest_id === questFilter)).length,
    rejected: allSubmissions.filter(s => s.status === "rejected" && (!questFilter || s.quest_id === questFilter)).length,
  };

  const timeAgo = (date: string): string => {
    const seconds = Math.floor((Date.now() - new Date(date).getTime()) / 1000);
    if (seconds < 60) return "just now";
    const minutes = Math.floor(seconds / 60);
    if (minutes < 60) return `${minutes}m ago`;
    const hours = Math.floor(minutes / 60);
    if (hours < 24) return `${hours}h ago`;
    const days = Math.floor(hours / 24);
    if (days === 1) return "yesterday";
    if (days < 7) return `${days}d ago`;
    return new Date(date).toLocaleDateString("en-GB", { day: "numeric", month: "short" });
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex items-center gap-3">
          {/* View toggle */}
          <div className="flex items-center gap-1 rounded-lg bg-muted p-1">
            <button onClick={() => { setView("quests"); setQuestFilter(null); }}
              className={`rounded-md px-3 py-1.5 text-xs font-medium transition-colors ${view === "quests" ? "bg-background text-foreground shadow-sm" : "text-muted-foreground hover:text-foreground"}`}>
              Quests
            </button>
            <button onClick={() => setView("submissions")}
              className={`rounded-md px-3 py-1.5 text-xs font-medium transition-colors flex items-center gap-1.5 ${view === "submissions" ? "bg-background text-foreground shadow-sm" : "text-muted-foreground hover:text-foreground"}`}>
              Submissions
              {totalPending > 0 && (
                <span className="inline-flex h-4.5 min-w-4.5 items-center justify-center rounded-full bg-amber-500 px-1.5 text-[10px] font-bold text-white tabular-nums">{totalPending}</span>
              )}
            </button>
          </div>

          {/* Context-specific filters */}
          {view === "quests" && (
            <div className="hidden sm:flex items-center gap-1 rounded-lg bg-muted/50 p-1">
              {(["active", "paused", "archived", "all"] as const).map((t) => (
                <button key={t} onClick={() => setFilter(t)}
                  className={`rounded-md px-2.5 py-1 text-[11px] font-medium transition-colors ${filter === t ? "bg-background text-foreground shadow-sm" : "text-muted-foreground hover:text-foreground"}`}>
                  {t.charAt(0).toUpperCase() + t.slice(1)}
                  <span className="ml-1 text-[10px] tabular-nums text-muted-foreground/60">{counts[t]}</span>
                </button>
              ))}
            </div>
          )}
          {view === "submissions" && (
            <div className="hidden sm:flex items-center gap-1 rounded-lg bg-muted/50 p-1">
              {(["pending", "approved", "rejected", "all"] as const).map((t) => (
                <button key={t} onClick={() => setSubFilter(t)}
                  className={`rounded-md px-2.5 py-1 text-[11px] font-medium transition-colors ${subFilter === t ? "bg-background text-foreground shadow-sm" : "text-muted-foreground hover:text-foreground"}`}>
                  {t.charAt(0).toUpperCase() + t.slice(1)}
                  <span className="ml-1 text-[10px] tabular-nums text-muted-foreground/60">{subCounts[t]}</span>
                </button>
              ))}
            </div>
          )}
        </div>
        {view === "quests" && <Button size="sm" onClick={openCreate}><Plus size={14} /> Create Quest</Button>}
      </div>

      {/* Pending submissions banner — only on quests view */}
      {view === "quests" && totalPending > 0 && !loading && (
        <div className="flex items-center justify-between rounded-xl border border-amber-500/20 bg-amber-500/5 px-5 py-3.5">
          <div className="flex items-center gap-3">
            <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-amber-500/10">
              <AlertCircle size={18} className="text-amber-500" />
            </div>
            <div>
              <p className="text-sm font-semibold text-foreground">{totalPending} submission{totalPending !== 1 ? "s" : ""} pending review</p>
              <p className="text-[11px] text-muted-foreground">Reps are waiting for approval on their quest proof</p>
            </div>
          </div>
          <Button size="sm" variant="outline" className="border-amber-500/30 text-amber-500 hover:bg-amber-500/10" onClick={() => {
            setView("submissions");
            setSubFilter("pending");
            setQuestFilter(null);
          }}>
            <Eye size={14} /> Review
          </Button>
        </div>
      )}

      {view === "quests" && (loading ? (
        <Card className="py-0 gap-0">
          <CardContent className="flex items-center justify-center py-16">
            <Loader2 size={20} className="animate-spin text-primary/60" />
            <span className="ml-3 text-sm text-muted-foreground">Loading quests...</span>
          </CardContent>
        </Card>
      ) : filtered.length === 0 ? (
        <Card className="py-0 gap-0">
          <CardContent className="flex flex-col items-center justify-center py-16 text-center">
            <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-primary/8 ring-1 ring-primary/10">
              <Swords size={20} className="text-primary/60" />
            </div>
            <p className="mt-4 text-sm font-medium text-foreground">No quests yet</p>
            <p className="mt-1 text-xs text-muted-foreground">Create quests to engage your reps</p>
            <Button size="sm" className="mt-4" onClick={openCreate}><Plus size={14} /> Create Quest</Button>
          </CardContent>
        </Card>
      ) : (
        <Card className="py-0 gap-0">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Quest</TableHead>
                <TableHead>Type</TableHead>
                <TableHead>Points</TableHead>
                <TableHead className="hidden md:table-cell">Completions</TableHead>
                <TableHead className="hidden lg:table-cell">Expires</TableHead>
                <TableHead>Status</TableHead>
                <TableHead className="text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {filtered.map((quest) => (
                <TableRow key={quest.id}>
                  <TableCell>
                    <div className="flex items-center gap-2">
                      <div>
                        <p className="text-sm font-medium text-foreground">{quest.title}</p>
                        {quest.description && <p className="mt-0.5 text-[11px] text-muted-foreground truncate max-w-[250px]">{quest.description}</p>}
                      </div>
                      {(quest.pending_count || 0) > 0 && (
                        <Badge variant="warning" className="text-[10px] tabular-nums shrink-0">{quest.pending_count} pending</Badge>
                      )}
                    </div>
                  </TableCell>
                  <TableCell><Badge variant="secondary" className="text-[10px]">{QUEST_TYPE_LABELS[quest.quest_type]}</Badge></TableCell>
                  <TableCell className="font-mono text-xs text-primary font-bold tabular-nums">+{quest.points_reward}</TableCell>
                  <TableCell className="hidden md:table-cell font-mono text-xs tabular-nums text-muted-foreground">
                    {quest.total_completed}{quest.max_total != null ? ` / ${quest.max_total}` : ""}
                  </TableCell>
                  <TableCell className="hidden lg:table-cell text-xs text-muted-foreground">
                    {quest.expires_at ? new Date(quest.expires_at).toLocaleDateString("en-GB", { day: "numeric", month: "short" }) : "\u2014"}
                  </TableCell>
                  <TableCell><Badge variant={QUEST_STATUS_VARIANT[quest.status]}>{quest.status}</Badge></TableCell>
                  <TableCell className="text-right">
                    <div className="flex items-center justify-end gap-1">
                      {(quest.pending_count || 0) > 0 ? (
                        <Button size="sm" variant="outline" className="h-7 text-[11px] border-amber-500/30 text-amber-500 hover:bg-amber-500/10" onClick={() => { setView("submissions"); setSubFilter("pending"); setQuestFilter(quest.id); }}>
                          <Eye size={12} /> Review {quest.pending_count}
                        </Button>
                      ) : (
                        <Button variant="ghost" size="icon-xs" onClick={() => { setView("submissions"); setSubFilter("all"); setQuestFilter(quest.id); }} title="View submissions"><Eye size={13} /></Button>
                      )}
                      <Button variant="ghost" size="icon-xs" onClick={() => openEdit(quest)} title="Edit"><Pencil size={13} /></Button>
                      <Button variant="ghost" size="icon-xs" onClick={() => handleDelete(quest.id)} className="text-muted-foreground hover:text-destructive" title="Archive"><Trash2 size={13} /></Button>
                    </div>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </Card>
      ))}

      {/* ── Global Submissions Feed ── */}
      {view === "submissions" && (
        <>
          {/* Quest filter chip */}
          {questFilter && (() => {
            const fq = quests.find(q => q.id === questFilter);
            return (
              <div className="flex items-center gap-2">
                <div className="inline-flex items-center gap-2 rounded-lg border border-border bg-muted/30 px-3 py-1.5">
                  <Filter size={12} className="text-muted-foreground" />
                  <span className="text-xs text-foreground font-medium">{fq?.title || "Quest"}</span>
                  <button onClick={() => setQuestFilter(null)} className="ml-1 rounded-full p-0.5 hover:bg-muted transition-colors">
                    <X size={12} className="text-muted-foreground" />
                  </button>
                </div>
              </div>
            );
          })()}

          {/* Batch approve bar */}
          {subCounts.pending >= 2 && subFilter === "pending" && (
            <div className="flex items-center justify-between rounded-xl border border-primary/20 bg-primary/5 px-5 py-3">
              <span className="text-sm text-muted-foreground">{subCounts.pending} submission{subCounts.pending !== 1 ? "s" : ""} awaiting review</span>
              <Button
                size="sm"
                disabled={reviewingId !== null}
                onClick={async () => {
                  const pending = filteredSubs.filter(s => s.status === "pending");
                  for (const sub of pending) { await handleReview(sub.id, "approved"); }
                }}
              >
                <CheckCircle2 size={14} /> Approve All
              </Button>
            </div>
          )}

          {/* Mobile status filter */}
          <div className="flex sm:hidden items-center gap-1 rounded-lg bg-muted p-1">
            {(["pending", "approved", "rejected", "all"] as const).map((t) => (
              <button key={t} onClick={() => setSubFilter(t)}
                className={`flex-1 rounded-md px-2 py-1.5 text-[11px] font-medium transition-colors ${subFilter === t ? "bg-background text-foreground shadow-sm" : "text-muted-foreground hover:text-foreground"}`}>
                {t.charAt(0).toUpperCase() + t.slice(1)}
                {subCounts[t] > 0 && <span className="ml-1 text-[10px] tabular-nums text-muted-foreground/60">{subCounts[t]}</span>}
              </button>
            ))}
          </div>

          {loadingAllSubs ? (
            <Card className="py-0 gap-0">
              <CardContent className="flex items-center justify-center py-16">
                <Loader2 size={20} className="animate-spin text-primary/60" />
                <span className="ml-3 text-sm text-muted-foreground">Loading submissions...</span>
              </CardContent>
            </Card>
          ) : filteredSubs.length === 0 ? (
            <Card className="py-0 gap-0">
              <CardContent className="flex flex-col items-center justify-center py-16 text-center">
                <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-primary/8 ring-1 ring-primary/10">
                  <Inbox size={20} className="text-primary/60" />
                </div>
                <p className="mt-4 text-sm font-medium text-foreground">
                  {subFilter === "pending" ? "No pending submissions" : "No submissions found"}
                </p>
                <p className="mt-1 text-xs text-muted-foreground">
                  {subFilter === "pending" ? "You're all caught up!" : "Try a different filter"}
                </p>
              </CardContent>
            </Card>
          ) : (
            <div className="space-y-3">
              {filteredSubs.map((sub) => {
                const proofUrl = sub.proof_url || sub.proof_text || "";
                const isTikTok = sub.proof_type === "tiktok_link";
                const isInstagram = sub.proof_type === "instagram_link";
                const isPlatformLink = isTikTok || isInstagram;
                const proofLabel = isTikTok ? "TikTok" : isInstagram ? "Instagram" : sub.proof_type === "screenshot" ? "Screenshot" : sub.proof_type === "url" ? "URL" : "Text";
                const isPending = sub.status === "pending";
                const questTitle = (sub.quest as RepQuest | undefined)?.title || "Unknown Quest";
                const questType = (sub.quest as RepQuest | undefined)?.quest_type;
                const eventName = (sub.quest as RepQuest & { event?: { name: string } | null } | undefined)?.event?.name;

                return (
                  <Card key={sub.id} className={`overflow-hidden transition-all ${isPending ? "ring-1 ring-amber-500/20 hover:ring-amber-500/30" : "opacity-80 hover:opacity-100"}`}>
                    <CardContent className="p-0">
                      <div className="flex flex-col sm:flex-row">
                        {/* Proof column */}
                        <div className="sm:w-56 shrink-0 bg-muted/10 border-b sm:border-b-0 sm:border-r border-border">
                          {sub.proof_type === "screenshot" && sub.proof_url ? (
                            <button
                              type="button"
                              className="relative w-full group cursor-zoom-in"
                              onClick={() => setLightboxUrl(sub.proof_url!)}
                            >
                              {/* eslint-disable-next-line @next/next/no-img-element */}
                              <img src={sub.proof_url} alt="Proof" className="w-full sm:h-48 object-contain bg-black/10" />
                              <div className="absolute inset-0 bg-black/0 group-hover:bg-black/30 transition-colors flex items-center justify-center">
                                <div className="opacity-0 group-hover:opacity-100 transition-opacity bg-white/10 backdrop-blur-sm rounded-full p-2.5 border border-white/20">
                                  <ZoomIn size={16} className="text-white" />
                                </div>
                              </div>
                            </button>
                          ) : (isPlatformLink || sub.proof_type === "url") && proofUrl ? (
                            <div className="p-5 flex flex-col items-center justify-center h-full min-h-[80px]">
                              {isTikTok ? <Music size={24} className="text-[#25F4EE] mb-2" /> : isInstagram ? <Camera size={24} className="text-[#E1306C] mb-2" /> : <LinkIcon size={24} className="text-primary mb-2" />}
                              <a href={proofUrl} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1.5 text-xs text-primary hover:underline break-all text-center">
                                <ExternalLink size={11} className="shrink-0" /> Open {proofLabel}
                              </a>
                            </div>
                          ) : sub.proof_type === "text" && sub.proof_text ? (
                            <div className="p-5 flex items-center justify-center h-full min-h-[80px]">
                              <p className="text-sm text-foreground/80 italic text-center line-clamp-3">&ldquo;{sub.proof_text}&rdquo;</p>
                            </div>
                          ) : (
                            <div className="p-5 flex items-center justify-center h-full min-h-[80px] text-muted-foreground/20">
                              <ImageLucide size={28} />
                            </div>
                          )}
                        </div>

                        {/* Details column */}
                        <div className="flex-1 p-4 flex flex-col gap-3">
                          {/* Top row: quest info + time */}
                          <div className="flex items-start justify-between gap-2">
                            <div className="flex items-center gap-2 flex-wrap">
                              <Badge variant="secondary" className="text-[10px] font-medium">
                                {questTitle}
                              </Badge>
                              {questType && (
                                <span className="text-[10px] text-muted-foreground">{QUEST_TYPE_LABELS[questType]}</span>
                              )}
                              {eventName && (
                                <span className="text-[10px] text-muted-foreground/60">{eventName}</span>
                              )}
                            </div>
                            <div className="flex items-center gap-1.5 shrink-0">
                              <Clock size={11} className="text-muted-foreground/50" />
                              <span className="text-[11px] text-muted-foreground tabular-nums">{timeAgo(sub.created_at)}</span>
                            </div>
                          </div>

                          {/* Rep info row */}
                          <div className="flex items-center gap-3">
                            {sub.rep?.photo_url ? (
                              /* eslint-disable-next-line @next/next/no-img-element */
                              <img src={sub.rep.photo_url} alt="" className="h-9 w-9 rounded-full object-cover ring-2 ring-border" />
                            ) : (
                              <div className="h-9 w-9 rounded-full bg-primary/10 flex items-center justify-center text-xs font-bold text-primary ring-2 ring-border">
                                {sub.rep?.first_name?.charAt(0) || "?"}
                              </div>
                            )}
                            <div>
                              <p className="text-sm font-semibold text-foreground leading-tight">
                                {sub.rep?.display_name || `${sub.rep?.first_name || ""} ${sub.rep?.last_name || ""}`.trim() || "Unknown"}
                              </p>
                              <div className="flex items-center gap-2 mt-0.5">
                                <Badge variant="outline" className="text-[9px] font-normal px-1.5 py-0">{proofLabel}</Badge>
                                <Badge variant={sub.status === "approved" ? "success" : sub.status === "rejected" ? "destructive" : "warning"} className="text-[9px] px-1.5 py-0">
                                  {sub.status}
                                </Badge>
                              </div>
                            </div>
                          </div>

                          {/* Actions */}
                          {isPending && (
                            <div className="mt-auto pt-1">
                              {rejectingId === sub.id ? (
                                <div className="space-y-2">
                                  <Textarea
                                    value={rejectReason}
                                    onChange={(e) => setRejectReason(e.target.value)}
                                    placeholder="Reason for rejection..."
                                    className="text-sm min-h-[50px]"
                                    autoFocus
                                  />
                                  <div className="flex items-center gap-2">
                                    <Button size="sm" variant="destructive" disabled={!rejectReason.trim() || reviewingId === sub.id}
                                      onClick={() => { handleReview(sub.id, "rejected", rejectReason.trim()); setRejectingId(null); setRejectReason(""); }}>
                                      {reviewingId === sub.id ? <Loader2 size={12} className="animate-spin" /> : <X size={12} />} Reject
                                    </Button>
                                    <Button size="sm" variant="ghost" onClick={() => { setRejectingId(null); setRejectReason(""); }}>Cancel</Button>
                                  </div>
                                </div>
                              ) : (
                                <div className="flex items-center gap-2">
                                  <Button size="sm" onClick={() => handleReview(sub.id, "approved")} disabled={reviewingId === sub.id}>
                                    {reviewingId === sub.id ? <Loader2 size={14} className="animate-spin" /> : <Check size={14} />} Approve
                                  </Button>
                                  <Button size="sm" variant="outline" onClick={() => setRejectingId(sub.id)} disabled={reviewingId === sub.id}>
                                    <X size={14} /> Reject
                                  </Button>
                                </div>
                              )}
                            </div>
                          )}
                          {sub.status === "approved" && (
                            <p className="text-xs text-success flex items-center gap-1.5"><CheckCircle2 size={12} /> Approved</p>
                          )}
                          {sub.status === "rejected" && (
                            <div>
                              <p className="text-xs text-destructive flex items-center gap-1.5"><X size={12} /> Rejected</p>
                              {sub.rejection_reason && <p className="text-[11px] text-muted-foreground mt-0.5">{sub.rejection_reason}</p>}
                            </div>
                          )}
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                );
              })}
            </div>
          )}
        </>
      )}

      {/* Create/Edit Dialog */}
      <Dialog open={showDialog} onOpenChange={setShowDialog}>
        <DialogContent className={dialogStep === "type" ? "max-w-xl" : "max-w-2xl max-h-[85vh] flex flex-col"}>
          <DialogHeader>
            <DialogTitle>{editId ? "Edit Quest" : dialogStep === "type" ? "New Quest" : "Create Quest"}</DialogTitle>
            <DialogDescription>
              {editId ? "Update this quest." : dialogStep === "type" ? "What should your reps do?" : `Set up your ${QUEST_TYPE_LABELS[questType].toLowerCase()} quest.`}
            </DialogDescription>
          </DialogHeader>

          {dialogStep === "type" ? (
            /* ── Type Selection ── */
            <div className="space-y-3 py-2">
              <div className="grid grid-cols-2 gap-3">
                {([
                  { type: "social_post" as QuestType, icon: Video, label: "Social Post", desc: "Reps recreate a reference TikTok or Instagram Reel" },
                  { type: "story_share" as QuestType, icon: Camera, label: "Story Share", desc: "Upload content for reps to share on their stories" },
                ] as const).map(({ type, icon: Icon, label, desc }) => (
                  <button key={type}
                    onClick={() => { handleQuestTypeChange(type); setDialogStep("form"); }}
                    className="group flex flex-col items-start gap-3 rounded-xl border-2 border-border p-5 text-left transition-all hover:border-primary/50 hover:bg-primary/[0.03] active:scale-[0.98]">
                    <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 ring-1 ring-primary/20 transition-colors group-hover:bg-primary/15">
                      <Icon size={18} className="text-primary" />
                    </div>
                    <div>
                      <p className="text-sm font-semibold text-foreground">{label}</p>
                      <p className="mt-1 text-xs text-muted-foreground leading-relaxed">{desc}</p>
                    </div>
                  </button>
                ))}
              </div>
              <button
                onClick={() => { handleQuestTypeChange("sales_milestone"); setDialogStep("form"); }}
                className="w-full flex items-center gap-4 rounded-xl border-2 border-border p-4 text-left transition-all hover:border-primary/50 hover:bg-primary/[0.03] active:scale-[0.98]">
                <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-emerald-500/10 ring-1 ring-emerald-500/20">
                  <Target size={18} className="text-emerald-500" />
                </div>
                <div>
                  <p className="text-sm font-semibold text-foreground">Sales Challenge</p>
                  <p className="mt-0.5 text-xs text-muted-foreground leading-relaxed">Set a sales target — progress tracks automatically as reps sell tickets</p>
                </div>
              </button>
              <div className="grid grid-cols-2 gap-3">
                {([
                  { type: "content_creation" as QuestType, icon: Sparkles, label: "Content Creation", desc: "Reps create original content" },
                  { type: "custom" as QuestType, icon: Swords, label: "Custom", desc: "Define your own quest" },
                ] as const).map(({ type, icon: Icon, label, desc }) => (
                  <button key={type}
                    onClick={() => { handleQuestTypeChange(type); setDialogStep("form"); }}
                    className="flex items-center gap-3 rounded-lg border border-border p-3 text-left transition-all hover:border-primary/40 hover:bg-primary/[0.02] active:scale-[0.98]">
                    <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-md bg-muted">
                      <Icon size={14} className="text-muted-foreground" />
                    </div>
                    <div>
                      <p className="text-xs font-medium text-foreground">{label}</p>
                      <p className="text-[11px] text-muted-foreground">{desc}</p>
                    </div>
                  </button>
                ))}
              </div>
            </div>
          ) : (
            /* ── Quest Form ── */
            <>
              {/* Navigation bar */}
              <div className="space-y-3">
                {!editId ? (
                  <button onClick={() => setDialogStep("type")}
                    className="flex items-center gap-2 text-xs text-muted-foreground hover:text-foreground transition-colors">
                    <ArrowLeft size={12} />
                    <span>Change type</span>
                    <Badge variant="secondary" className="text-[10px]">{QUEST_TYPE_LABELS[questType]}</Badge>
                  </button>
                ) : (
                  <Badge variant="secondary" className="text-[10px]">{QUEST_TYPE_LABELS[questType]}</Badge>
                )}
                <div className="flex items-center gap-1 rounded-lg bg-muted/50 p-1">
                  {QUEST_FORM_TABS[questType].map((tab, i) => (
                    <button key={tab} onClick={() => setFormTab(i)}
                      className={`flex-1 rounded-md px-3 py-1.5 text-xs font-medium transition-all ${
                        i === formTab
                          ? "bg-background text-foreground shadow-sm"
                          : "text-muted-foreground hover:text-foreground"
                      }`}>
                      {tab}
                    </button>
                  ))}
                </div>
              </div>

              {/* Tab content */}
              <div className="flex-1 overflow-y-auto space-y-4 pr-1">
                {(() => {
                  const currentTabLabel = QUEST_FORM_TABS[questType][formTab];
                  return (<>

                {/* ── Tab: Details (all types) ── */}
                {currentTabLabel === "Details" && (
                  <div className="space-y-4">
                    <div className="space-y-2">
                      <Label>Title *</Label>
                      <Input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="e.g. Share Our Event on Stories" autoFocus />
                    </div>
                    <div className="space-y-2">
                      <Label>Description</Label>
                      <Textarea value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Brief summary shown on quest cards" rows={3} />
                    </div>
                    <div className="space-y-2">
                      <Label>Linked Event</Label>
                      <select
                        value={eventId}
                        onChange={(e) => setEventId(e.target.value)}
                        className="w-full rounded-lg border border-border bg-background px-3 py-2 text-sm text-foreground"
                      >
                        <option value="">None (global quest)</option>
                        {events.map((ev) => (
                          <option key={ev.id} value={ev.id}>{ev.name}</option>
                        ))}
                      </select>
                      <p className="text-[10px] text-muted-foreground">
                        {questType === "sales_milestone"
                          ? "Tie sales tracking to a specific event, or leave blank to count all sales"
                          : "Link to an event so reps get a share URL that takes followers directly to it"}
                      </p>
                    </div>
                  </div>
                )}

                {/* ── Tab: Platform (social_post / content_creation) ── */}
                {currentTabLabel === "Platform" && (
                  <div className="space-y-4">
                    <div className="grid grid-cols-3 gap-2">
                      {([
                        { value: "tiktok" as const, label: "TikTok" },
                        { value: "instagram" as const, label: "Instagram" },
                        { value: "any" as const, label: "Either" },
                      ]).map(({ value, label }) => (
                        <button key={value}
                          type="button"
                          onClick={() => setPlatform(value)}
                          className={`flex items-center justify-center gap-2 rounded-lg border-2 px-3 py-2.5 text-sm font-medium transition-all ${
                            platform === value
                              ? "border-primary bg-primary/5 text-primary shadow-sm"
                              : "border-border text-muted-foreground hover:border-primary/30 hover:text-foreground"
                          }`}>
                          {label}
                        </button>
                      ))}
                    </div>
                    <div className="space-y-2">
                      <Label className="flex items-center gap-1.5">
                        <ExternalLink size={12} />
                        Reference Post Link
                      </Label>
                      <Input
                        value={referenceUrl}
                        onChange={(e) => setReferenceUrl(e.target.value)}
                        placeholder={
                          platform === "tiktok" ? "https://www.tiktok.com/@user/video/..."
                            : platform === "instagram" ? "https://www.instagram.com/reel/..."
                            : "Paste a TikTok or Instagram link"
                        }
                      />
                      <p className="text-[10px] text-muted-foreground">
                        {questType === "social_post"
                          ? "Link to the post reps should recreate — shown as a CTA in the quest"
                          : "Optional reference for reps to use as inspiration"}
                      </p>
                    </div>
                    {platform === "tiktok" && (
                      <div className="flex items-center justify-between rounded-lg border border-border p-3">
                        <div className="flex items-center gap-2">
                          <Music size={14} className="text-muted-foreground" />
                          <div>
                            <p className="text-sm font-medium text-foreground">Uses a Specific Sound</p>
                            <p className="text-[11px] text-muted-foreground">The reference post has a sound reps should use</p>
                          </div>
                        </div>
                        <Switch checked={usesSound} onCheckedChange={setUsesSound} />
                      </div>
                    )}
                    <div className="space-y-2">
                      <Label>How to Complete</Label>
                      <Textarea
                        value={instructions}
                        onChange={(e) => { setInstructions(e.target.value); setInstructionsAutoGenerated(false); }}
                        placeholder="Step-by-step instructions shown to reps"
                        rows={3}
                      />
                      {instructionsAutoGenerated && (
                        <p className="text-[10px] text-muted-foreground">Auto-generated — edit freely</p>
                      )}
                    </div>
                  </div>
                )}

                {/* ── Tab: Content (story_share + social_post + content_creation) ── */}
                {currentTabLabel === "Content" && (
                  <div className="space-y-4">
                    <p className="text-xs text-muted-foreground">
                      {questType === "story_share"
                        ? "Upload the image or video reps will download and share on their story. You can add one or both."
                        : "Optionally upload an image or video for reps to download. Useful when they need specific content to post."}
                    </p>
                    <ImageUpload
                      label={questType === "story_share" ? "Story Image" : "Downloadable Image"}
                      value={imageUrl}
                      onChange={setImageUrl}
                      uploadKey={editId ? `quest_${editId}_image` : undefined}
                    />
                    <div className="space-y-2">
                      <Label className="flex items-center gap-1.5"><Video size={12} /> {questType === "story_share" ? "Story Video" : "Downloadable Video"}</Label>
                      {videoUrl ? (
                        <div className="space-y-2">
                          {isMuxPlaybackId(videoUrl) ? (
                            <div className="rounded-lg overflow-hidden border border-border">
                              <MuxPlayer playbackId={videoUrl} streamType="on-demand" autoPlay={false} muted className="w-full aspect-video" />
                            </div>
                          ) : (
                            <div className="rounded-lg overflow-hidden border border-border">
                              <video src={videoUrl} controls className="w-full aspect-video" />
                            </div>
                          )}
                          <Button variant="outline" size="sm" onClick={() => setVideoUrl("")}>
                            <X size={12} /> Remove Video
                          </Button>
                        </div>
                      ) : videoUploading ? (
                        <div className="rounded-lg border border-border p-4 space-y-2">
                          <div className="flex items-center gap-2">
                            <Loader2 size={14} className="animate-spin text-primary" />
                            <span className="text-sm text-muted-foreground">{videoStatus}</span>
                          </div>
                          {videoProgress > 0 && (
                            <div className="h-1.5 rounded-full bg-muted overflow-hidden">
                              <div className="h-full rounded-full bg-primary transition-all" style={{ width: `${videoProgress}%` }} />
                            </div>
                          )}
                        </div>
                      ) : (
                        <label className="flex flex-col items-center gap-2 rounded-lg border-2 border-dashed border-border bg-muted/20 py-6 cursor-pointer transition-colors hover:border-primary/40 hover:bg-muted/30">
                          <Upload size={18} className="text-muted-foreground" />
                          <span className="text-xs text-muted-foreground font-medium">Click to upload a video</span>
                          <span className="text-[10px] text-muted-foreground/60">MP4, MOV, WebM — max 200MB</span>
                          <input
                            ref={videoInputRef}
                            type="file"
                            accept="video/*"
                            className="hidden"
                            onChange={(e) => { const file = e.target.files?.[0]; if (file) handleVideoUpload(file); e.target.value = ""; }}
                          />
                        </label>
                      )}
                      {videoError && (
                        <div className="flex items-start gap-1.5 rounded-md border border-destructive/20 bg-destructive/5 px-3 py-2">
                          <AlertCircle size={12} className="text-destructive mt-0.5 shrink-0" />
                          <p className="text-xs text-destructive">{videoError}</p>
                        </div>
                      )}
                    </div>
                  </div>
                )}

                {/* ── Tab: Setup (custom) ── */}
                {currentTabLabel === "Setup" && (
                  <div className="space-y-4">
                    <div className="space-y-2">
                      <Label>Platform</Label>
                      <div className="grid grid-cols-3 gap-2">
                        {([
                          { value: "tiktok" as const, label: "TikTok" },
                          { value: "instagram" as const, label: "Instagram" },
                          { value: "any" as const, label: "Either" },
                        ]).map(({ value, label }) => (
                          <button key={value}
                            type="button"
                            onClick={() => setPlatform(value)}
                            className={`flex items-center justify-center gap-2 rounded-lg border-2 px-3 py-2.5 text-sm font-medium transition-all ${
                              platform === value
                                ? "border-primary bg-primary/5 text-primary shadow-sm"
                                : "border-border text-muted-foreground hover:border-primary/30 hover:text-foreground"
                            }`}>
                            {label}
                          </button>
                        ))}
                      </div>
                    </div>
                    <div className="space-y-2">
                      <Label>How to Complete</Label>
                      <Textarea
                        value={instructions}
                        onChange={(e) => { setInstructions(e.target.value); setInstructionsAutoGenerated(false); }}
                        placeholder="Write your own instructions for reps"
                        rows={4}
                      />
                    </div>
                  </div>
                )}

                {/* ── Tab: Target (sales_milestone) ── */}
                {currentTabLabel === "Target" && (
                  <div className="space-y-4">
                    <div className="space-y-2">
                      <Label>Sales Target *</Label>
                      <Input
                        type="number"
                        value={salesTarget}
                        onChange={(e) => setSalesTarget(e.target.value)}
                        placeholder="e.g. 5"
                        min="1"
                      />
                      <p className="text-[10px] text-muted-foreground">Number of sales a rep needs to achieve. Progress tracks automatically.</p>
                    </div>
                  </div>
                )}

                {/* ── Tab: Publish (all types) ── */}
                {currentTabLabel === "Publish" && (
                  <div className="space-y-4">
                    <div className="space-y-2">
                      <ImageUpload
                        label="Card Banner"
                        value={bannerImageUrl}
                        onChange={setBannerImageUrl}
                        uploadKey={editId ? `quest_${editId}_banner` : undefined}
                      />
                      <p className="text-[10px] text-muted-foreground">Optional decorative image shown on the quest card background</p>
                    </div>

                    <div className="flex items-center gap-3">
                      <div className="h-px flex-1 bg-border" />
                      <span className="text-[10px] uppercase tracking-widest text-muted-foreground/60 font-medium">Rewards</span>
                      <div className="h-px flex-1 bg-border" />
                    </div>
                    <div className="grid grid-cols-2 gap-4">
                      <div className="space-y-2">
                        <Label>XP Reward <span className="text-[10px] text-muted-foreground font-normal">(set by type)</span></Label>
                        <Input
                          type="number"
                          value={String(platformConfig.xp_per_quest_type[questType] ?? platformConfig.xp_per_quest_type.custom)}
                          readOnly
                          className="bg-muted/30 cursor-not-allowed"
                        />
                      </div>
                      <div className="space-y-2">
                        <Label>Currency Reward</Label>
                        <Input type="number" value={currencyReward} onChange={(e) => setCurrencyReward(e.target.value)} min="0" />
                      </div>
                    </div>

                    <div className="flex items-center gap-3">
                      <div className="h-px flex-1 bg-border" />
                      <span className="text-[10px] uppercase tracking-widest text-muted-foreground/60 font-medium">Settings</span>
                      <div className="h-px flex-1 bg-border" />
                    </div>
                    <div className="grid grid-cols-2 gap-4">
                      <div className="space-y-2">
                        <Label>Max Completions per Rep</Label>
                        <Input type="number" value={maxCompletions} onChange={(e) => setMaxCompletions(e.target.value)} placeholder="Unlimited" min="1" />
                      </div>
                      <div className="space-y-2">
                        <Label>Expires At</Label>
                        <Input type="datetime-local" value={expiresAt} onChange={(e) => setExpiresAt(e.target.value)} />
                      </div>
                    </div>
                    <div className="flex items-center justify-between rounded-lg border border-border p-3">
                      <div>
                        <p className="text-sm font-medium text-foreground">Notify Reps</p>
                        <p className="text-[11px] text-muted-foreground">Send notification when this quest goes live</p>
                      </div>
                      <Switch checked={notifyReps} onCheckedChange={setNotifyReps} />
                    </div>
                  </div>
                )}
                  </>);
                })()}
              </div>

              <DialogFooter>
                {formTab > 0 && (
                  <Button variant="ghost" onClick={() => setFormTab(formTab - 1)} className="mr-auto">
                    <ArrowLeft size={14} /> Back
                  </Button>
                )}
                {formTab < QUEST_FORM_TABS[questType].length - 1 ? (
                  <Button onClick={() => setFormTab(formTab + 1)} disabled={formTab === 0 && !title.trim()}>
                    Next
                  </Button>
                ) : (
                  <>
                    <Button variant="outline" onClick={() => setShowDialog(false)}>Cancel</Button>
                    <Button onClick={handleSave} disabled={saving || !title.trim()}>
                      {saving && <Loader2 size={14} className="animate-spin" />}
                      {saving ? "Saving..." : editId ? "Save Changes" : "Create Quest"}
                    </Button>
                  </>
                )}
              </DialogFooter>
            </>
          )}
        </DialogContent>
      </Dialog>

      {/* ── Image Lightbox ── */}
      {lightboxUrl && (
        <div
          className="fixed inset-0 z-[100] flex items-center justify-center bg-black/80 backdrop-blur-sm cursor-zoom-out"
          onClick={() => setLightboxUrl(null)}
        >
          <button onClick={() => setLightboxUrl(null)} className="absolute top-4 right-4 h-10 w-10 rounded-full bg-white/10 border border-white/20 flex items-center justify-center text-white hover:bg-white/20 transition-colors">
            <X size={18} />
          </button>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src={lightboxUrl} alt="Proof" className="max-w-[90vw] max-h-[85vh] rounded-xl shadow-2xl object-contain" onClick={(e) => e.stopPropagation()} />
        </div>
      )}

    </div>
  );
}
